shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar
  - semver
catalog:
  '@iconify-json/streamline-cyber': ^1.2.2
  marked: ^18.0.10
  sharp: ^0.35.2
catalogs:
  cli:
    dotenv: ^17.4.2
    to-ico: ^1.1.5
    tsx: ^4.23.12

  lint:
    '@antfu/eslint-config': ^9.3.0
    '@typescript-eslint/parser': ^8.67.0
    eslint: ^10.8.1

  types:
    '@types/node': ^26.2.0
    '@types/to-ico': ^1.1.3
    typescript: ^6.0.3
    vue-tsc: ^3.3.11

  void:
    '@void/md': ^0.10.12
    '@void/vue': ^0.10.12
    vite: ^8.2.2
    void: ^0.10.12
    vue: ^3.5.41

  website:
    '@iconify-json/ph': ^1.2.2
    '@vueuse/core': ^14.4.0
    motion-v: ^2.4.0
    unocss: ^66.8.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - eslint
  - sqlite3
  - unrs-resolver
  - workerd

peerDependencyRules:
  allowAny:
    - vite
    - vitest
