name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 22
          cache: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - run: pnpm void deploy
        env:
          VOID_TOKEN: ${{ secrets.VOID_TOKEN }}
          VOID_PROJECT: ${{ secrets.VOID_PROJECT }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          ARTICLE_REPO: https://github.com/liangmiQwQ/tree-hole
          INFO_REPO: https://github.com/liangmiQwQ/me
